### ISSUE TITLE
onClientConnectionState() - status=22 clientIf=5

### ISSUE THREAD

**Issue by gaoyouhuang** [NordicSemiconductor/Android-BLE-Library#105]
hi~
![image](https://user-images.githubusercontent.com/16697706/57265323-b9c52600-70a9-11e9-9a6d-d2b097add6e8.png)

Now I pair my mobile phone with the device and connect it with Bluetooth. Then I delete the matching information of the device. Then the mobile phone connects the device through Bluetooth, and it finds that the device can not connect, and returns to state 22. What does state 22 mean?

**Comment by gaoyouhuang** [comment]
Now what I do is, when I encounter the state 22, remove Bond and connect Gatt, but I don't think that's a good way to do that.

**Comment by philips77** [comment]
Error 22 (0x16) is: https://github.com/NordicSemiconductor/Android-BLE-Library/blob/5e0e2f08c309a6de2376d9b8705c83f9e9a80d56/ble/src/main/java/no/nordicsemi/android/ble/error/GattError.java#L38
If you want to remove bond information you have to do this on the phone and on the device together. Otherwise one side will try to re-initiate encryption and will fail. Android doesn't remove bond information automatically when this happens. User has to do this in Bluetooth settings, or using this hidden method to remove bonding. Also, error 22 may happen for some other reasons than the one described.

**Comment by gaoyouhuang** [comment]
thank you very much

**Comment by georrge1994** [comment]
@philips77 you are the big professional in BT. Can you advice me? I get timeout disconnection for bond device after 30 seconds. If I clear cache on client device, error will gone and it works until I restart me gatt server. I can not refresh cache for all clients, I don't have access to some of clients. How I can find and resolve the real reason of local host side? Anyway thank you for your lib
