### ISSUE TITLE
WriteRequest write characteristic is too slow.

### ISSUE THREAD

**Issue by gksrb4** [NordicSemiconductor/Android-BLE-Library#135]
I try to 
`final WriteRequest request = writeCharacteristic(mRXCharacteristic, data);				request.enqueue();`

![image](https://user-images.githubusercontent.com/49257699/68831832-bb277900-06f2-11ea-8cec-262c52ccc8e0.png)
It takes almost 100 ms to send each 20 bytes data.
The connection interval is fast enough. how can I improve speed?

**Comment by philips77** [comment]
Hi @gksrb4,
Yes, we are aware of this issue. It will be addressed in version 2.2. The problem is, that in the current version all BLE requests are performed from the main thread, while the gatt callbacks use their own thread, so there is a thread change before every write operation. For other operations this is acceptable, but for write without response this decreases the speed significantly. The new version will no longer use the main thread for everything, but I have to do a lot of testing, a specially on the older phones, before releasing it. The reason for using the main thread was that in the old days the BLE seemed to be more stable and there were less 133 errors popping up. But that also might have been a side effect of the delay caused be switching the thread.

**Comment by gksrb4** [comment]
Okay, thanks to reply.
