### ISSUE TITLE
ServiceChangedIndicationsRequest not set on Android 10

### ISSUE THREAD

**Issue by Christophe668** [NordicSemiconductor/Android-BLE-Library#148]
Hi @philips77!

I have a question concerning Android 10 and your library on both 2.1.1 and 2.2.0-alpha02.
I can see that the `Request.newEnableServiceChangedIndicationsRequest` is not set on Android 10 here: 
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/develop/ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java#L1747

Is that something that is now automatically done on Android 10 or should it be also set manually like on Android 8 and 9?

Thanks in advance,

Christophe

**Comment by philips77** [comment]
Around one and half year ago I reported this issue to Google, that at some point they have disabled automatic subscription for Service Changed indication during bonding. The fix was introduced here: https://android-review.googlesource.com/c/platform/system/bt/+/714261
Indeed, I tried using a Pixel 4 with Android 10 and the Service Changed indications are enabled automatically.
