### ISSUE TITLE
Cannot be used with Kotlin?

### ISSUE THREAD

**Issue by travisgriggs** [NordicSemiconductor/Android-BLE-Library#169]
I'm trying to create a ValueChangedCallback class in Kotlin, e.g.

    class FungibleValueChangedCallback(handler:Handler):ValueChangedCallback(handler) {
        ...
    }

However, I get the error 

    Cannot access '<init>': it is package-private in ValueChangedCallback

This seems to have come up before: https://stackoverflow.com/questions/53413776/is-there-a-solution-to-cannot-access-init-it-is-private-in-xyz

Is there anyway this can be changed to make it compatible with Kotlin?

**Comment by philips77** [comment]
This is by design. You should use methods of BleManager to create this object:
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/e95a814f4c0ecd08a75e5f0e53c68e2b8dbdf70c/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L610
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/e95a814f4c0ecd08a75e5f0e53c68e2b8dbdf70c/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L628
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/e95a814f4c0ecd08a75e5f0e53c68e2b8dbdf70c/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L644
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/e95a814f4c0ecd08a75e5f0e53c68e2b8dbdf70c/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L660

**Comment by philips77** [comment]
Also, this library is fully compatible with Kotlin.
