### ISSUE TITLE
Sample app

### ISSUE THREAD

**Issue by openmotion** [NordicSemiconductor/Android-BLE-Library#227]
Can you provide a sample app chat tutorial ? I want to make a simple communication between two android BLE smartphones .
Thanks

**Comment by philips77** [comment]
One of the phones needs to [advertise](https://developer.android.com/reference/kotlin/android/bluetooth/le/BluetoothLeAdvertiser) as [connectable](https://developer.android.com/reference/kotlin/android/bluetooth/le/AdvertiseSettings.Builder#setConnectable(kotlin.Boolean)) device and have a [GATT server](https://github.com/NordicSemiconductor/Android-BLE-Library#adding-gatt-server-support) opened with service of your design.
The other phone needs to ask in runtime for Fine Location Permission (in order to be able to scan for BLE devices), [scan for the first phone's advertising packet](https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library) and [connect and send data](https://github.com/NordicSemiconductor/Android-BLE-Library#usage).

For now we don not have any sample app showing the peripheral side (advertising and GATT server). Sorry.
