### ISSUE TITLE
Bonded device takes more time to retrieve isDeviceReady, is it normal?

### ISSUE THREAD

**Issue by jose-alvessh** [NordicSemiconductor/Android-BLE-Library#261]
I'm using the version 2.1.0 of this library to connect some BLE sensors to an Android device. 
We are testing two different versions of FW, one with native-pair and bonding implemented and another that only differs on this respect - no native-pair neither bonding implemented (I have to scan for it each time I use the app on this version of FW). 

I'm using this piece of code for both:

```java
ConnectRequest connectRequest = connect(bleDevice);
connectRequest.useAutoConnect(false).enqueue();
```

and then I'm waiting to receive the onDeviceReady() callback from the BLEManagerCallbacks to proceed with the normal flow of my App. 

So the question is regarding the time that each FW takes until the onDeviceReady() callback is received. 
Using the native-pair version with the sensor already paired and bonded to the Android device takes more time (more than 1 second) to receive this callback than when I'm using the no native-pair version. 
As the device was already bonded this behaviour seem really strange and as I use multiple sensors it is delaying the normal behaviour of the app. I was expecting that the connection times would be reduced with the device already bonded.

Is this an expected behaviour? Does this delay is related with the encryption of the link between sensors and the Android device? Is there any solution that I can implement to make the connection faster using a bonded device with an encrypted link? 

I tried to figure it out analysing the code but couldn't get any answer on it. I'm sorry if it is an expected behaviour.
Thanks in advance.

**Comment by philips77** [comment]
Hello,
Really sorry for coming here so late, I was busy with other tasks and didn't have time unfortunately to look into BLE library.

The time difference you experience is mainly caused by this method:
https://github.com/NordicSemiconductor/Android-BLE-Library/blob/12441cb4fe0074c3e2267500bd28621d288cb398/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L648-L651
The link points to tag *2.1.0*, so you may check this method in your implementation.
By default, for bonded device the service discovery is delayed 1.6 sec. This is to make sure (almost...), that possible Service Change indication would be received before we actually call `gatt.discoverServices()`. Otherwise, `onServicesDiscovered` would return outdated services and following automatic service discovery would be ignored. However, if you are not sending SC indication, and assume your device will never send it (at least not before updating the app), you may lower the delays and fine tune the delay. You may also try with 0 if it works for you. I recommend checking on different phones, also lower-end devices.

Hopefully this answers your question.
