### ISSUE TITLE
Seemless connection

### ISSUE THREAD

**Issue by mattinger** [NordicSemiconductor/Android-BLE-Library#301]
I'm trying to connect to a device with a known PIN (which for right now is hardcoded, but would be a calculated value).  However, no matter what i do, i can't seem to bypass the system dialogs.  I get the first "Pair and Connect" prompt.  Click that, then have to click "Pair" on the ensuing dialog.  Then the original dialog "Pair and Connect" button lights up again, but i don't actually have to click it.  i can just swipe it away.

I've done this in my BleManager:

```kotlin
    override fun onPairingRequestReceived(device: BluetoothDevice, variant: Int) {
        super.onPairingRequestReceived(device, variant)
        Log.d(LOG_TAG, "Setting PIN")
        device.setPin(BLUETOOTH_PIN.toByteArray())
        device.createBond()
    }
```

And like i said, i can bond, but it's not seamless.  And i feel like the succession of dialogs would confuse the user when they don't really need to enter a pin to get paired.

**Comment by philips77** [comment]
Yes, that is true. I also wan't able to get rid of the native pairing dialog. 
Any app could listen to Pairing Request broadcast and display any popup it wants and with the PIN provided do what you do. Android Settings is an example of such app. From your app you can't hide the dialog in another app, unless it has some API to do so.

There are better ways to make pairing automatic, e.g. using NFC. Android supports OOB over NFC since around Android 6. You may also use LESC. But for recommendations about security I would recommend checking Bluetooth spec, or asking on DevZone, as I don't have sufficient knowledge.
