### ISSUE TITLE
BLE Scan Not working on android 12

### ISSUE THREAD

**Issue by kirankirvelrm** [NordicSemiconductor/Android-BLE-Library#330]
I use this library in my application.
Now I am testing the application with android 12 and in scan only it's not working. Not showing a single device in a scan. I use UDID based scan and connectivity.

**Comment by Yazazzello** [comment]
If check the error code from library - you'll see that it's related to permissions. On Android 12 Bluetooth permissions have been changed. check the documentation - https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

**Comment by philips77** [comment]
Hello,
Thank you for answering this old issue, I must have missed it.
This library has nothing to do with scanning for BLE Devices, but @Yazazzello is right. Check your permissions and location service. If you need to scan for iBeacons or Eddystone beacons, make sure you request for both `BLUETOOTH_SCAN` and `ACCESS_FINE_LOCATION` permissions. Otherwise, use the `neverForLocation` flag in the Android Manifest.
