### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by jswn0203** [NordicSemiconductor/Android-BLE-Library#337]
Some mobile phones cannot be connected for the first time when bluetooth is turned off, and they can only be connected again when they manually set the setting for pairing. May I ask why

**Comment by philips77** [comment]
You need to scan before connecting. The device has to advertise, and needs to be scanned by the phone. 
Bluetooth LE MAC address is in fact 48+1 bit long. The 49th bit is a type: *public* or *private*. If a device is not bonded, and hasn't been scanned since last time Bluetooth was turned on, Android assumes *public* address type, and even if you know the 48-bit MAC address, the connection will fail. There is currently no way to pass the address type to Android other than scanning.
Bonded devices have this type saved together with the Long Term Key, so you should always be able to connect to a bonded device, assuming it advertises.
