### ISSUE TITLE
How to send more than 20 bytes of data with 1.2.0 ?

### ISSUE THREAD

**Issue by hyoungtaikkim** [NordicSemiconductor/Android-BLE-Library#57]
Hi,

I need to send/receive more than 20 bytes of data through BLE. I read https://github.com/NordicSemiconductor/Android-BLE-Library/issues/3 for sending more than 20  bytes. However I would like to use Android-BLE-Library 1.2.0 for some reason. Could you let me know where to modify in 1.2.0 ? 

Anyway did you try all 3 approaches in  https://github.com/NordicSemiconductor/Android-BLE-Library/issues/3 at Android-BLE-Library 2.*.*?

Thanks.

**Comment by philips77** [comment]
In 1.2.0, what I would do, is to split data before calling writeCharacteristic and then call it multiple times. You may find an example in nRF Toolbox all in bleLib1 branch in UartManager.

**Comment by philips77** [comment]
A link: https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/ble_lib/1.x/app/src/main/java/no/nordicsemi/android/nrftoolbox/uart/UARTManager.java

**Comment by hyoungtaikkim** [comment]
Hi,

Sorry to keep bothering you. In our project, we only need for client (Android phone) to communicate with one type of server (device) through BLE. I have also verified that I can make the packet size larger through request_mtu(517) up to 514 (517 - 3) both for client (min sdk is Lollipop) and the server (device). So what do you think about enlarging the packet size up to 514 first and send/receive data. If the data size is bigger than 514, can I still chop it to many packets through queue? Does that sound reasonable with Android-BLE-Library 1.2.0 ? Or mtu should be only 23 (20 available) for chopping the data to many packets?

Thanks.

**Comment by philips77** [comment]
Yes, you may use Android-BLE-Library 1.2.0. Longer MTU (higher than 23) is supported on Android since Android 5 Lollipop. Use the [requestMtu](https://github.com/NordicSemiconductor/Android-BLE-Library/blob/version/1x/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L890) method to request higher MTU. You should get a [callback](https://github.com/NordicSemiconductor/Android-BLE-Library/blob/version/1x/ble/src/main/java/no/nordicsemi/android/ble/BleManager.java#L1165) when MTU selected.

**Comment by philips77** [comment]
Longer MTUs must also be supported by the other side. The callback will give you the MTU both side have agreed on.

**Comment by hyoungtaikkim** [comment]
Thanks again. ;)
